name: Project_EPP_ArbiKodraj

dependencies:

  # Python Version
- python=3.7 

  # Packages for stats, math, 
  # scientific computing, data manipulation
- numpy     
- scipy
- pandas
- numba

  # Visualization
- matplotlib
- seaborn

  # Machine Learning
- scikit-learn=0.23.2
- tensorflow

  # Additional Packages
- jupyterlab=6.0.3
- requests
- bs4
- pip

- pip:
  - sklearn2pmml
  - yfinance


